import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Systems sidebar: autogenerated from `docs/systems` directory
  systemsSidebar: [
    {
      type: 'category',
      label: 'Systems',
      items: [
        {type: 'autogenerated', dirName: 'systems'},
      ],
    },
  ],

  // Plugin System sidebar: comprehensive plugin documentation
  pluginsSidebar: [
    {
      type: 'category',
      label: 'Plugin System',
      items: [
        'plugins/index',
        'plugins/audio-plugin-guide',
        'plugins/video-plugin-guide',
        'plugins/architecture',
        'plugins/api-reference',
        'plugins/troubleshooting',
      ],
    },
  ],

  // Guides sidebar: development guides and tutorials
  guidesSidebar: [
    {
      type: 'category',
      label: 'Development Guides',
      items: [
        'guides/debug-system',
        'guides/rendering-api',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
